In [18]:
import pandas as pd

In [19]:
books = pd.read_csv("books_with_categories.csv")

In [20]:
from transformers import pipeline
classifier = pipeline(
    "text-classification", 
    model="j-hartmann/emotion-english-distilroberta-base", 
    top_k=None, 
    device="mps")
classifier("the weather is stormy")

Device set to use mps

[[{'label': 'sadness', 'score': 0.6374793648719788},
  {'label': 'anger', 'score': 0.11776242405176163},
  {'label': 'neutral', 'score': 0.09243372082710266},
  {'label': 'fear', 'score': 0.06229207664728165},
  {'label': 'joy', 'score': 0.050331879407167435},
  {'label': 'surprise', 'score': 0.03461725637316704},
  {'label': 'disgust', 'score': 0.005083305295556784}]]

In [21]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [22]:
# sentiment analysis on whole description all at once
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548416018486023},
  {'label': 'neutral', 'score': 0.16985218226909637},
  {'label': 'sadness', 'score': 0.11640842258930206},
  {'label': 'surprise', 'score': 0.020700668916106224},
  {'label': 'disgust', 'score': 0.019100721925497055},
  {'label': 'joy', 'score': 0.015161274932324886},
  {'label': 'anger', 'score': 0.003935148473829031}]]

In [23]:
# sentiment analysis on individual sentences all together
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.14038576185703278},
  {'label': 'fear', 'score': 0.06816207617521286},
  {'label': 'joy', 'score': 0.04794240742921829},
  {'label': 'anger', 'score': 0.009156345389783382},
  {'label': 'disgust', 'score': 0.0026284754276275635},
  {'label': 'sadness', 'score': 0.002122161677107215}],
 [{'label': 'neutral', 'score': 0.44937148690223694},
  {'label': 'disgust', 'score': 0.27359095215797424},
  {'label': 'joy', 'score': 0.10908271372318268},
  {'label': 'sadness', 'score': 0.09362737089395523},
  {'label': 'anger', 'score': 0.04047819972038269},
  {'label': 'surprise', 'score': 0.026970235630869865},
  {'label': 'fear', 'score': 0.006879072170704603}],
 [{'label': 'neutral', 'score': 0.6462159752845764},
  {'label': 'sadness', 'score': 0.24273347854614258},
  {'label': 'disgust', 'score': 0.043422628194093704},
  {'label': 'surprise', 'score': 0.028300482779741287},
  {'label': 'joy', 'score': 0.014211437664926052},
  {'label': 'fear', 'score': 0.01408409047871828},
  {'label': 'anger', 'score': 0.011031875386834145}],
 [{'label': 'fear', 'score': 0.9281686544418335},
  {'label': 'anger', 'score': 0.03219059482216835},
  {'label': 'neutral', 'score': 0.012808652594685555},
  {'label': 'sadness', 'score': 0.008756853640079498},
  {'label': 'surprise', 'score': 0.008597896434366703},
  {'label': 'disgust', 'score': 0.008431806229054928},
  {'label': 'joy', 'score': 0.0010455807205289602}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104183927178383},
  {'label': 'disgust', 'score': 0.006480604410171509},
  {'label': 'fear', 'score': 0.005394005216658115},
  {'label': 'surprise', 'score': 0.0022869426757097244},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338795587420464}],
 [{'label': 'joy', 'score': 0.932797908782959},
  {'label': 'disgust', 'score': 0.03771720454096794},
  {'label': 'neutral', 'score': 0.015891890972852707},
  {'label': 'sadness', 'score': 0.00644450169056654},
  {'label': 'anger', 'score': 0.005024981219321489},
  {'label': 'surprise', 'score': 0.001581208547577262},
  {'label': 'fear', 'score': 0.0005423070979304612}],
 [{'label': 'joy', 'score': 0.6528701782226562},
  {'label': 'neutral', 'score': 0.2542751133441925},
  {'label': 'surprise', 'score': 0.06808319687843323},
  {'label': 'sadness', 'score': 0.009909004904329777},
  {'label': 'disgust', 'score': 0.006512219551950693},
  {'label': 'anger', 'score': 0.0048213135451078415},
  {'label': 'fear', 'score': 0.003529020817950368}],
 [{'label': 'neutral', 'score': 0.5494772791862488},
  {'label': 'sadness', 'score': 0.11169011890888214},
  {'label': 'disgust', 'score': 0.1040065661072731},
  {'label': 'surprise', 'score': 0.07876542210578918},
  {'label': 'anger', 'score': 0.06413351744413376},
  {'label': 'fear', 'score': 0.05136272311210632},
  {'label': 'joy', 'score': 0.040564339607954025}]]

In [24]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [25]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [26]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296027541160583},
 {'label': 'neutral', 'score': 0.14038576185703278},
 {'label': 'fear', 'score': 0.06816207617521286},
 {'label': 'joy', 'score': 0.04794240742921829},
 {'label': 'anger', 'score': 0.009156345389783382},
 {'label': 'disgust', 'score': 0.0026284754276275635},
 {'label': 'sadness', 'score': 0.002122161677107215}]

In [27]:
predictions

[[{'label': 'surprise', 'score': 0.7296027541160583},
  {'label': 'neutral', 'score': 0.14038576185703278},
  {'label': 'fear', 'score': 0.06816207617521286},
  {'label': 'joy', 'score': 0.04794240742921829},
  {'label': 'anger', 'score': 0.009156345389783382},
  {'label': 'disgust', 'score': 0.0026284754276275635},
  {'label': 'sadness', 'score': 0.002122161677107215}],
 [{'label': 'neutral', 'score': 0.44937148690223694},
  {'label': 'disgust', 'score': 0.27359095215797424},
  {'label': 'joy', 'score': 0.10908271372318268},
  {'label': 'sadness', 'score': 0.09362737089395523},
  {'label': 'anger', 'score': 0.04047819972038269},
  {'label': 'surprise', 'score': 0.026970235630869865},
  {'label': 'fear', 'score': 0.006879072170704603}],
 [{'label': 'neutral', 'score': 0.6462159752845764},
  {'label': 'sadness', 'score': 0.24273347854614258},
  {'label': 'disgust', 'score': 0.043422628194093704},
  {'label': 'surprise', 'score': 0.028300482779741287},
  {'label': 'joy', 'score': 0.014211437664926052},
  {'label': 'fear', 'score': 0.01408409047871828},
  {'label': 'anger', 'score': 0.011031875386834145}],
 [{'label': 'fear', 'score': 0.9281686544418335},
  {'label': 'anger', 'score': 0.03219059482216835},
  {'label': 'neutral', 'score': 0.012808652594685555},
  {'label': 'sadness', 'score': 0.008756853640079498},
  {'label': 'surprise', 'score': 0.008597896434366703},
  {'label': 'disgust', 'score': 0.008431806229054928},
  {'label': 'joy', 'score': 0.0010455807205289602}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104183927178383},
  {'label': 'disgust', 'score': 0.006480604410171509},
  {'label': 'fear', 'score': 0.005394005216658115},
  {'label': 'surprise', 'score': 0.0022869426757097244},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338795587420464}],
 [{'label': 'joy', 'score': 0.932797908782959},
  {'label': 'disgust', 'score': 0.03771720454096794},
  {'label': 'neutral', 'score': 0.015891890972852707},
  {'label': 'sadness', 'score': 0.00644450169056654},
  {'label': 'anger', 'score': 0.005024981219321489},
  {'label': 'surprise', 'score': 0.001581208547577262},
  {'label': 'fear', 'score': 0.0005423070979304612}],
 [{'label': 'joy', 'score': 0.6528701782226562},
  {'label': 'neutral', 'score': 0.2542751133441925},
  {'label': 'surprise', 'score': 0.06808319687843323},
  {'label': 'sadness', 'score': 0.009909004904329777},
  {'label': 'disgust', 'score': 0.006512219551950693},
  {'label': 'anger', 'score': 0.0048213135451078415},
  {'label': 'fear', 'score': 0.003529020817950368}],
 [{'label': 'neutral', 'score': 0.5494772791862488},
  {'label': 'sadness', 'score': 0.11169011890888214},
  {'label': 'disgust', 'score': 0.1040065661072731},
  {'label': 'surprise', 'score': 0.07876542210578918},
  {'label': 'anger', 'score': 0.06413351744413376},
  {'label': 'fear', 'score': 0.05136272311210632},
  {'label': 'joy', 'score': 0.040564339607954025}]]

In [28]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156345389783382},
 {'label': 'disgust', 'score': 0.0026284754276275635},
 {'label': 'fear', 'score': 0.06816207617521286},
 {'label': 'joy', 'score': 0.04794240742921829},
 {'label': 'neutral', 'score': 0.14038576185703278},
 {'label': 'sadness', 'score': 0.002122161677107215},
 {'label': 'surprise', 'score': 0.7296027541160583}]

In [29]:
"""
This cell contains the implementation of the function `calculate_emotion_scores` which calculates the maximum emotion scores for each emotion label from the given predictions.
The `emotion_labels` list contains the possible emotion labels: "anger", "disgust", "fear", "joy", "sadness", "surprise", and "neutral".
The `isbn` list is initialized as an empty list, which can be used to store ISBN numbers of books if needed.
The `emotion_scores` dictionary is initialized with keys as emotion labels and values as empty lists, which can be used to store emotion scores for each label.
The `calculate_emotion_scores` function takes a list of predictions as input. Each prediction is a list of dictionaries, where each dictionary contains an emotion label and its corresponding score.
The function processes the predictions to calculate the maximum score for each emotion label. It returns a dictionary with emotion labels as keys and their corresponding maximum scores as values.
"""

import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [31]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)

    max_scores = calculate_max_emotion_scores(predictions)
    
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [32]:
emotion_scores

{'anger': [0.06413351744413376,
  0.6126189827919006,
  0.06413351744413376,
  0.35148346424102783,
  0.08141227066516876,
  0.2322249561548233,
  0.5381839871406555,
  0.06413351744413376,
  0.3006700873374939,
  0.06413351744413376],
 'disgust': [0.27359095215797424,
  0.3482859134674072,
  0.1040065661072731,
  0.15072251856327057,
  0.1844949573278427,
  0.727174699306488,
  0.1558549851179123,
  0.1040065661072731,
  0.2794809937477112,
  0.17792674899101257],
 'fear': [0.9281686544418335,
  0.942527711391449,
  0.9723208546638489,
  0.36070698499679565,
  0.09504343569278717,
  0.05136272311210632,
  0.7474279403686523,
  0.4044962227344513,
  0.9155241250991821,
  0.05136272311210632],
 'joy': [0.932797908782959,
  0.70442134141922,
  0.7672367691993713,
  0.2518807351589203,
  0.040564339607954025,
  0.04337587207555771,
  0.8725650310516357,
  0.040564339607954025,
  0.040564339607954025,
  0.040564339607954025],
 'sadness': [0.6462159752845764,
  0.8879395127296448,
  0.5494772791862488,
  0.7326863408088684,
  0.8843892216682434,
  0.6213923096656799,
  0.7121947407722473,
  0.5494772791862488,
  0.8402897715568542,
  0.8603722453117371],
 'surprise': [0.9671574234962463,
  0.11169011890888214,
  0.11169011890888214,
  0.11169011890888214,
  0.4758804738521576,
  0.11169011890888214,
  0.4079981744289398,
  0.8202820420265198,
  0.35445961356163025,
  0.11169011890888214],
 'neutral': [0.7296027541160583,
  0.25254514813423157,
  0.07876542210578918,
  0.07876542210578918,
  0.07876542210578918,
  0.27190297842025757,
  0.07876542210578918,
  0.23448777198791504,
  0.13561475276947021,
  0.07876542210578918]}

In [37]:
# The following code block initializes the emotion labels, ISBN list, and emotion scores dictionary.
# It then iterates over the range of the length of the books DataFrame, appending the ISBN numbers to the ISBN list.
# For each book description, it splits the description into sentences and uses the classifier to predict the emotions for each sentence.
# The maximum emotion scores are calculated using the calculate_max_emotion_scores function.
# These maximum scores are then appended to the corresponding lists in the emotion_scores dictionary.

from tqdm import tqdm

 # Initialize emotion labels, ISBN list, and emotion scores dictionary
emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

# Iterate over the range of the length of the books DataFrame
for i in tqdm(range(len(books))):
    # Append the ISBN number to the ISBN list
    isbn.append(books["isbn13"][i])
    
    # Split the book description into sentences
    sentences = books["description"][i].split(".")
    
    # Predict the emotions for each sentence using the classifier
    predictions = classifier(sentences)
    
    # Calculate the maximum emotion scores
    max_scores = calculate_max_emotion_scores(predictions)
    
    # Append the maximum scores to the corresponding lists in the emotion_scores dictionary
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [05:55<00:00, 14.60it/s]

In [39]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [40]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928169,0.932798,0.646216,0.967157,0.729603,9780002005883
1,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765,9780006178736
3,0.351483,0.150723,0.360707,0.251881,0.732686,0.111690,0.078765,9780006280897
4,0.081412,0.184495,0.095043,0.040564,0.884389,0.475880,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148209,0.030643,0.919165,0.255169,0.853722,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400264,0.883198,0.111690,0.227764,9788173031014
5194,0.009997,0.009929,0.339217,0.947779,0.375756,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459268,0.759456,0.951104,0.368110,0.078765,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059

In [41]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [42]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928169,0.932798,0.646216,0.967157,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Fiction,0.351483,0.150723,0.360707,0.251881,0.732686,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Fiction,0.081412,0.184495,0.095043,0.040564,0.884389,0.475880,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148209,0.030643,0.919165,0.255169,0.853722,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Fiction,0.064134,0.114383,0.051363,0.400264,0.883198,0.111690,0.227764
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339217,0.947779,0.375756,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459268,0.759456,0.951104,0.368110,0.078765
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765

In [43]:
books.to_csv("books_with_emotions.csv", index = False)